### ISSUE TITLE
Language Variant File Names should be aligned with ISO 3166

### ISSUE THREAD

**Issue by vanthome** [adamwdraper/Numeral-js#75] opened 2013-07-05 09:39 UTC
This ISO standard defines country codes in capitals:
http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
Also this standard defines language tags in the form de-AT or en-GB etc.
http://en.wikipedia.org/wiki/IETF_language_tag

Same point I made here for momen.js:

https://github.com/timrwood/moment/issues/869

Currently, the lang files mix upper and lower case for the variant suffix which is not good I think.

**Comment by wachunei** [comment] 2016-01-23 15:07
I come from the future: Is this handled? I want to use `navigator.language` but I want unhandled cases (say `es-CL`, `es-AR`, etc.) to fallback to `es`.

**Comment by adamwdraper** [comment] 2016-12-07 07:12
Duplicate of #55

**Closed by adamwdraper** 2016-12-07 07:12 UTC
