### ISSUE TITLE
Incorrect suffix assignment when rounding up with '0a' type formats

### ISSUE THREAD

**Issue by samnau** [adamwdraper/Numeral-js#283] opened 2015-08-17 16:10 UTC
I found an interesting issue that happens when entering a value in the thousands, but technically should round up to the millions when displayed with 'format()'. For example:

```
var amount = 999999;
numeral(amount).format('0a');
```

The output of this would be "1000k", but a user would probably expect this to display as '1m' when rounded. Mathematically, it is still correct, but typically a user wouldn't expect to see a shortened value of '1000k'. The issue happens for any number that would round up to the next prefix. So 999999999 would display as '1000m' instead of '1b'.

I was able to work around this by intercepting the formatted value and making a literal assignment of the output to the expected rounded display value based on the suffix returned by numeral, but I know that's probably not the preferred solution. (In my case I was uppercasing the suffix for display, FYI)

```
var formattedString = numeral(amount).format('$0a').toUpperCase();
var leadingFormattedNumber = numeral().unformat(formattedString);
var wronglyRounded = leadingFormattedNumber === 1000 

var roundedValues = {
                    'K' : '$1M',
                    'M' : '$1B',
                    'B' : '$1T'
                };

if(wronglyRounded){
                    moneySuffix = formattedString.slice(-1);
                    return roundedValues[moneySuffix];
                }
```

I just wanted to bring this issue to your attention. Thank you for making such a useful JS library!

**Comment by jamiter** [comment] 2015-09-15 10:44
Hi, this repository is no longer maintained. You can get an improved version here: https://github.com/foretagsplatsen/numbro. That one is still maintained and you can report your issues there.

**Comment by samnau** [comment] 2015-09-15 22:12
@jamiter  Hmm. What is the difference between numeral and numbro?

**Comment by jamiter** [comment] 2015-09-16 09:21
numeral was no longer maintained, so numbro was created as a fork. So numbro is basically the same thing, but maintained. Just look at the code and documentation, it's the same :)

**Comment by samnau** [comment] 2015-09-16 14:53
@jamiter  Actually it will be maintained. It's just been on hold. Here's an update directly from the creator:

"I haven't updated numeral in a while, because I have been busy moving out to San Franciso and working at this startup Fountain. I do still plan on maintaining the project and hope to make some time for it by the end of the month."

**Comment by jamiter** [comment] 2015-09-16 18:54
@samnau, thats good news. Maybe he can work together with the guys at numbro to get al the latest updates in. If you have personal contact with him you can maybe suggest this.

The reason I call this unmaintained is bacause there hasnt been a commit since 2 years and tickets aren't being answered. So the numbro package was a good initiative for the time being.

**Comment by adamwdraper** [comment] 2016-12-21 05:06
Duplicate of #187

**Closed by adamwdraper** 2016-12-21 05:06 UTC
Labels: bug
