### ISSUE TITLE
prefix and suffix

### ISSUE THREAD

**Issue by ikhsan017** [adamwdraper/Numeral-js#81] opened 2013-08-22 21:37 UTC
is there any chance to be able to add prefix or suffix in the format?

something like
    $ 0[.]00 */pcs

can become to
    $ 5.42 /pcs

btw, very useful lib :)

**Comment by adamwdraper** [comment] 2016-12-07 07:13
Duplicate of #396

**Closed by adamwdraper** 2016-12-07 07:13 UTC
Labels: enhancement
