### ISSUE TITLE
Formatting of Negative currencies with negative symbol at the end ($ n-)

### ISSUE THREAD

**Issue by anilchempath** [adamwdraper/Numeral-js#93] opened 2013-09-26 06:03 UTC
We are trying to format the negative curecny for nl-NL . So the negative pattern is  ' $ n- '  .
 So I have formatted the currecny  as `numeral("-102300.00").format("$10,00.00-")` but its giving wrong  results .  Am i doing some thing wrong how can I achieve this.

Thanks in Advance .

**Comment by adamwdraper** [comment] 2016-12-07 07:20
Duplicate of #89

**Closed by adamwdraper** 2016-12-07 07:20 UTC
